### ISSUE TITLE
Bulk edit

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/phthiraptera-transcription#15]
To change:
Improve colours/layout
Select items over multiple pages
Sort browse by barcode date

**Comment by PaulKiddle** [comment]
Any examples of good/bad interfaces?

**Comment by PaulKiddle** [comment]
Bulk edit rather than bulk create - ties into #11

**Comment by Allan-Louise** [comment]
The iCollections transcription interface had this functionality (copy data from one transcription entry and paste into the next entry etc) - Pete Wing used this interface so he can provide more information.

**Comment by Allan-Louise** [comment]
FYI - some thoughts about bulk edit function for reference but I realize that some aspects would be hard to implement, and some points may have already been discussed elsewhere:

- Bulk edits may also be more effective if you have a long series of records with the same data.

- Currently, if multiple people are working on the app they will get the next available record so a series would be split across each user, which may reduce the effectiveness of the bulk edit tool for each user. For the Phthiraptera collection a series with the same data is generally limited to around 7-10 slides but for other collections, especially UK collections, series could be much larger.

- The ability to copy a single field or multiple fields could be useful as specimens from a collector could be grouped but have different localities.  

- iCollections assigned batches of specimens to each digitiser which meant that series would be kept together. This is obviously complex to do and would required user profiles and assigned specimens and would only be feasible if a known group of people were working on the project i.e. the digitisation team.
